name: Flutter Web Build and Deploy

on:
  push:
    branches:
      - main # Agar aapki main branch ka naam 'master' hai, toh ise change kar lein

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Web Support
        run: flutter config --enable-web

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web App
        # DHYAAN DEIN: Niche 'Railway-TA-Form' ki jagah apne exact GitHub Repo ka naam likhein
        run: flutter build web --release --base-href /Railway-TA-Form/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          
